### ISSUE TITLE
Handling nested wiki-links

### ISSUE THREAD

**Issue by zomars** [juanfrank77/foam-eleventy-template#4]
I'm tinkering with a possible solution to fix nested wiki-links.

Right know I need to transform the current output:

```html 
[<a href="todo" title="Todo">todo</a>]

```

into something like this:
```html
<a href="/bubbles/todo" title="Todo">todo</a>
```

or something like this:

```html
<a href="./todo" title="Todo">todo</a>
```

I don't know which would be a better solution, suggestions are welcome 🙏

**Comment by juanfrank77** [comment]
The first option is the one I used with the Netlify redirects ha! 
But in the local env, there's an option if I remember correctly that allows us to use a base URL on the links so that when a link is clicked it is appended to the "base" instead of "already formed URL" which isn't what we're looking for.

**Comment by zomars** [comment]
@juanfrank77 is that an eleventy or a foam config?

**Comment by juanfrank77** [comment]
Well according to the creator of Foam itself, it's not a thing specific to Foam because the links get displayed either as "/inbox" or "/inbox/" depending on how they're generated (i.e. Jekyll or Eleventy)

I think the config is somewhere in the Eleventy docs to make them absolute instead of a relative path.

**Comment by zomars** [comment]
I found [this comment](https://github.com/markdown-it/markdown-it/issues/548#issuecomment-623078580) in the markdown-it repo, I think this could be a good solution.

**Comment by juanfrank77** [comment]
@zomars Thanks for doing this detective work!! I looked into the comment thread and I think that's the way to go 🙌
